#!/usr/bin/env python

import csv
import requests
import io

url = 'http://ourairports.com/data/airports.csv'

fpin = io.StringIO(requests.get(url).text)

headers = ['Name', 'Latitude', 'Longitude', 'Details']

with open('data.csv', 'w', encoding='UTF-8') as fpout:
    writer = csv.writer(fpout)
    writer.writerow(headers)

    reader = csv.reader(fpin)
    headers = next(reader)

    for row in reader:
        entry = dict(zip(headers, row))

        if entry['iata_code']:
            name = entry['name']
            latitude = entry['latitude_deg']
            longitude = entry['longitude_deg']
            details = entry['iata_code']

            writer.writerow([name, latitude, longitude, details])
